### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by kpcyrd**
This updates both the error-chain and widestring dependency to the latest version.

### CODE REVIEW

**Comment by liranringel** [comment]
Last time I bumped error-chain I found that it had a breaking change that broke trust-dns.
Could you check against trust-dns?

**Comment by kpcyrd** [comment]
@bluejekyll can you have a look if this patch would work for you?

**Comment by bluejekyll** [comment]
Yes, I’ll try and do this today. Trust-DNS moves away from error-chain and uses failure now, so I don’t anticipate any issues.

**Comment by bluejekyll** [comment]
So this will cause a minor break:

```console
error[E0599]: no method named `context` found for type `ipconfig::error::Error` in the current scope
   --> crates/resolver/src/error.rs:132:11
    |
132 |         e.context(ResolveErrorKind::Message("failed to read from registry"))
    |           ^^^^^^^
    |
    = note: the method `context` exists but the following trait bounds were not satisfied:
            `&ipconfig::error::Error : failure::Fail`
            `&mut ipconfig::error::Error : failure::Fail`
            `ipconfig::error::Error : failure::Fail
```

We can fix trust-dns downstream, so just an FYI.

**Comment by kpcyrd** [comment]
@bluejekyll so this is a breaking change, but you would be ok with releasing this patch as 0.2.0, right?

**Comment by liranringel** [comment]
Why do you want to bump these deps versions?
I consider stop using `error-chain` and make some more changes for 0.2.

**Comment by kpcyrd** [comment]
I'm packaging a crate that depends on ipconfig for debian and to support cross compilation we also package windows crates (and also because writing patches to remove windows specific dependencies is a lot of work).

Depending on an outdated version for error-chain, widestring and winreg means I have to package those outdated versions as well (along with their dependencies). There's a process in debian-rust to do that, but we need explicit approval from the ftp-masters.

If possible I would prefer a 0.2.0 release with this patch and a 0.3.0 release without error-chain and additional changes, but that's up to you of course.

**Comment by liranringel** [comment]
I've made some changes.
1. The error type no longer uses `error-chain`.
2. #26 which probably won't break your code.
3. Upgraded to Rust 2018 and fixed clippy warnings.

I hope it won't break your code. I believe the removal of `error-chain` was necessary, as there are talks about [deprecation ](https://github.com/rust-lang-nursery/failure/issues/181), and it was unstable for too long (I don't want to make breaking changes every time `error-chain` makes them).

Thank you for the PR :)

**Comment by kpcyrd** [comment]
Awesome, thank you! :)

**Pull request merged**
